using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace BloodBankDAL.Repository.Query.Transaction
{
    public class T12233 : CommonDAL
    {
        public DataTable GetGridData(string unitno, string lang, string language)
        {
            return Query($"SELECT DISTINCT T12022.T_UNIT_NO,  T12033.T_VIRUS_CODE,  T12033.T_LANG2_NAME VIRUS_DESC,  T01009.T_USER_NAME VIROLOGY_TEST_BY,  DECODE(T_POS2_VERIFY, '1', 'No', '2', 'Yes')T_POS2_VERIFY,  T01009.T_EMP_CODE T_POS1_VERIFIED_BY_CODE,    T12034.T_ENTRY_USER, (select DISTINCT T_USER_NAME FROM T12034  JOIN T01009 ON T12034.T_ENTRY_USER= T01009.T_EMP_CODE WHERE T12034.T_UNIT_NO='{unitno}')USER_NAME_BY,  T01009.T_USER_NAME T_POS1_VERIFIED_BY,  TO_CHAR(T12034.T_POS1_VERIFIED_DATE,'dd/MM/yyyy')T_POS1_VERIFIED_DATE,  T12034.T_SEND_FLAG,  T12034.T_LAB_REQ_NO,  TO_CHAR(T12034.T_LAB_REQ_DATE,'dd/MM/yyyy')T_LAB_REQ_DATE FROM T12022,  T12033,  T01009,  T12034 WHERE T12022.T_UNIT_NO  = '{unitno}' AND T12034.T_POS1_VERIFIED_BY = T01009.T_EMP_CODE AND T12033.T_VIRUS_CODE       = T12034.T_VIRUS_CODE AND T12022.T_UNIT_NO          = T12034.T_UNIT_NO AND TO_NUMBER(REGEXP_REPLACE(T12034.T_VIRUS_RESULT, '[^.0-9]', '')) BETWEEN 1 AND 1000 AND T12034.T_VIRUS_RESULT NOT IN ('M562') AND T_POS1_VERIFY  ='1' ORDER BY T_VIRUS_CODE");
            // return Query($"SELECT DISTINCT T12022.T_UNIT_NO,T12033.T_VIRUS_CODE,T12033.T_LANG{lang}_NAME VIRUS_DESC,T01009.T_USER_NAME{language} VIROLOGY_TEST_BY, DECODE(T_POS2_VERIFY, '1', 'No', '2', 'Yes')T_POS2_VERIFY,T01009.T_EMP_CODE T_POS1_VERIFIED_BY_CODE,T01009.T_USER_NAME{language} T_POS1_VERIFIED_BY, TO_CHAR(T12034.T_POS1_VERIFIED_DATE,'dd/MM/yyyy')T_POS1_VERIFIED_DATE, T12034.T_SEND_FLAG, T12034.T_LAB_REQ_NO, TO_CHAR(T12034.T_LAB_REQ_DATE,'dd/MM/yyyy')T_LAB_REQ_DATE FROM T12022, T12033, T01009, T12034 WHERE T12022.T_UNIT_NO = '{unitno}' AND T12034.T_ENTRY_USER = T01009.T_EMP_CODE AND T12034.T_POS1_VERIFIED_BY = T01009.T_EMP_CODE AND T12033.T_VIRUS_CODE = T12034.T_VIRUS_CODE AND T12022.T_UNIT_NO = T12034.T_UNIT_NO AND TO_NUMBER(REGEXP_REPLACE(T12034.T_VIRUS_RESULT, '[^.0-9]', '')) BETWEEN 1 AND 1000 AND T12034.T_VIRUS_RESULT NOT IN ('M562') AND T_POS1_VERIFY='1' ORDER BY T_VIRUS_CODE");
        }


        public DataTable GetDataCheck(string unitno, string lang, string language, string value)
        {
            return Query($"SELECT DISTINCT T12022.T_UNIT_NO,T12033.T_VIRUS_CODE,T12033.T_LANG{lang}_NAME VIRUS_DESC,T01009.T_USER_NAME{language} VIROLOGY_TEST_BY, DECODE(T_POS2_VERIFY, '1', 'No', '2', 'Yes')T_POS2_VERIFY,T01009.T_USER_NAME{language} T_POS1_VERIFIED_BY, TO_CHAR(T12034.T_POS1_VERIFIED_DATE,'dd/MM/yyyy')T_POS1_VERIFIED_DATE, T12034.T_SEND_FLAG, T12034.T_LAB_REQ_NO, TO_CHAR(T12034.T_LAB_REQ_DATE,'dd/MM/yyyy')T_LAB_REQ_DATE FROM T12022, T12033, T01009, T12034 WHERE T12022.T_UNIT_NO = '{unitno}' AND T12034.T_ENTRY_USER = T01009.T_EMP_CODE AND T12034.T_POS1_VERIFIED_BY = T01009.T_EMP_CODE AND T12033.T_VIRUS_CODE = T12034.T_VIRUS_CODE AND T12022.T_UNIT_NO = T12034.T_UNIT_NO AND T12034.T_VIRUS_RESULT='{value}' AND T12034.T_VIRUS_RESULT NOT IN ('M562') AND T_POS1_VERIFY='1' ORDER BY T_VIRUS_CODE");
        }

        public DataTable GetDataCheck_03_04(string unitno, string lang, string language)
        {
            return Query($"SELECT DISTINCT T12022.T_UNIT_NO,T12033.T_VIRUS_CODE,T12033.T_LANG{lang}_NAME VIRUS_DESC,T01009.T_USER_NAME{language} VIROLOGY_TEST_BY, DECODE(T_POS2_VERIFY, '1', 'No', '2', 'Yes')T_POS2_VERIFY,T01009.T_USER_NAME{language} T_POS1_VERIFIED_BY, TO_CHAR(T12034.T_POS1_VERIFIED_DATE,'dd/MM/yyyy')T_POS1_VERIFIED_DATE, T12034.T_SEND_FLAG, T12034.T_LAB_REQ_NO, TO_CHAR(T12034.T_LAB_REQ_DATE,'dd/MM/yyyy')T_LAB_REQ_DATE FROM T12022, T12033, T01009, T12034 WHERE T12022.T_UNIT_NO = '{unitno}' AND T12034.T_ENTRY_USER = T01009.T_EMP_CODE AND T12034.T_POS1_VERIFIED_BY = T01009.T_EMP_CODE AND T12033.T_VIRUS_CODE = T12034.T_VIRUS_CODE AND T12022.T_UNIT_NO = T12034.T_UNIT_NO AND T12034.T_VIRUS_RESULT in ('03','04') AND T12034.T_VIRUS_RESULT NOT IN ('M562') AND T_POS1_VERIFY='1' ORDER BY T_VIRUS_CODE");
      
        }
        public DataTable GetVerifyData(string lang)
        {
            //return Query($"SELECT  '1' T_POS2_VERIFY,CASE WHEN '{lang}'='1' THEN 'نعم فعلا' ELSE 'YES' END T_VERIFY FROM DUAL UNION SELECT '2' T_POS2_VERIFY, CASE WHEN '{lang}' = '1' THEN 'لا' ELSE 'NO' END T_VERIFY FROM DUAL");
            return Query($"SELECT  '2' T_POS2_VERIFY,CASE WHEN '{lang}'='1' THEN 'نعم فعلا' ELSE 'YES' END T_VERIFY FROM DUAL UNION SELECT '1' T_POS2_VERIFY, CASE WHEN '{lang}' = '1' THEN 'لا' ELSE 'NO' END T_VERIFY FROM DUAL");
        }

        public DataTable GetUnitData()
        {
            return Query($"SELECT DISTINCT T12034.T_UNIT_NO,TO_CHAR(T12022.T_DONATION_DATE,'dd-MM-yyyy')T_DONATION_DATE FROM T12022,T12034 WHERE T12034.T_POS = '1' AND T12022.T_UNIT_NO = T12034.T_UNIT_NO");
        }

        public bool Insert_T13016(string T_ENTRY_USER, string T_LAB_REQ_NO, string T_ANALYSIS_CODE)
        {
            return Command($"INSERT INTO T13016 (T_ENTRY_USER,T_ENTRY_DATE,T_REQUEST_NO,T_ANALYSIS_CODE,T_WS_CODE, T_GROUP_FLAG ) VALUES ('{T_ENTRY_USER}', TRUNC(SYSDATE), '{T_LAB_REQ_NO}', '{T_ANALYSIS_CODE}', '22', NULL)");
        }
        public bool UpdateT12019(string T_VIOROLOGY_RESULT, string T_UNIT_NO)
        {
            return Command($"UPDATE T12019 SET T_VIOROLOGY_RESULT='{T_VIOROLOGY_RESULT}',T_VIRO_DATE=TRUNC(SYSDATE),T_VIRO_TIME=TO_CHAR(SYSDATE,'HH24MI') WHERE T_UNIT_NO='{T_UNIT_NO}'");
        }
        public bool UpdateT12034( string T_POS2_VERIFY, string T_SEND_FLAG,string T_LAB_REQ_NO, string T_UNIT_NO, string T_VIRUS_CODE,string user)
        {
            return Command($"UPDATE T12034 SET T_POS2_VERIFY='{T_POS2_VERIFY}',T_SEND_FLAG='{T_SEND_FLAG}',T_LAB_REQ_NO='{T_LAB_REQ_NO}',T_LAB_REQ_DATE=TRUNC(SYSDATE),T_POS2_VERIFIED_BY='{user}',T_POS2_VERIFIED_DATE=TRUNC(SYSDATE) WHERE T_UNIT_NO='{T_UNIT_NO}' AND T_VIRUS_CODE='{T_VIRUS_CODE}'");
        }
        //'{T_POS1_VERIFIED_DATE.ToString("dd-MMM-yyyy")}'
        public bool UpdateT12075(string T_VIOROLOGY_RESULT, string T_UNIT_NO)
        {
            return Command($"UPDATE T12075 SET T_VIROLOGY_RESULT='{T_VIOROLOGY_RESULT}' WHERE T_UNIT_NO='{T_UNIT_NO}'");
        }

        public bool InsertT12223(string user, string unitNo, string sitecode)
        {
            DataTable dt = new DataTable();
            dt = Query(
                $"SELECT T_UNIT_NO,T_ABO_CODE,TO_CHAR(T_DONATION_DATE,'MM/dd/yyyy')T_DONATION_DATE,TO_CHAR(T_EXPIRY_DATE,'MM/dd/yyyy')T_EXPIRY_DATE,T_PRODUCT_CODE FROM T12019 WHERE T_UNIT_NO = '{unitNo}'");
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                var productCode = dt.Rows[i]["T_PRODUCT_CODE"].ToString();
                var bloodGroupCode = dt.Rows[i]["T_ABO_CODE"].ToString();
                var donationDate = dt.Rows[i]["T_DONATION_DATE"].ToString();
                var expiryDate = dt.Rows[i]["T_EXPIRY_DATE"].ToString();

                Command($"INSERT INTO T12223 (T_ENTRY_USER,T_ENTRY_DATE,T_BB_STOCK_ID,T_UNIT_NO,T_PRODUCT_CODE,T_BLOOD_GROUP_CODE,T_DONATION_DATE,T_EXPIRY_DATE,T_BLOOD_STATUS,T_SITE_CODE) VALUES ('{user}',TRUNC(SYSDATE),(SELECT NVL(MAX(T_BB_STOCK_ID),0)+1 T_BB_STOCK_ID FROM T12223),'{unitNo}','{productCode}','{bloodGroupCode}',TO_DATE('{donationDate}', 'MM/DD/YYYY'),TO_DATE('{expiryDate}', 'MM/DD/YYYY'),'2','{sitecode}')");

            }

            return true;
        }
    }
}