using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using BloodBankDAL.Model;

namespace BloodBankDAL.Repository.Query.Transaction
{
    public class T12300:CommonDAL
    {
        public DataTable GetPatDetailsData(string lang, string patNo)
        {
            return Query($"SELECT T03001.T_PAT_NO,T12012.T_PAT_NO PAT_12,T12012.T_REQUISITION, to_char( T12012.T_REQUEST_DATE, 'DD-MON-YYYY')T_REQUEST_DATE,T12012.T_REQUEST_TIME,(SELECT NVL(MAX(T_REQUEST_NO),0) FROM T12012 WHERE T12012.T_PAT_NO ='{patNo}')RQID_12,  T03001.T_NTNLTY_ID,  T03001.T_FIRST_LANG{lang}_NAME  ||' ' || T03001.T_FATHER_LANG{lang}_NAME ||' '  ||T03001.T_GFATHER_LANG{lang}_NAME  ||' '  || T03001.T_FAMILY_LANG{lang}_NAME PAT_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE,T03001.T_BIRTH_DATE) / 12, 0) YRS, TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, T03001.T_BIRTH_DATE), 12), 0) MOS, T03001.T_GENDER T_SEX, T02006.T_LANG{lang}_NAME GENDER,  T03001.T_NTNLTY_CODE, T02003.T_LANG{lang}_NAME NATIONALITY  FROM  T03001       LEFT JOIN T02006 ON T03001.T_GENDER =T02006.T_SEX_CODE  LEFT JOIN T02003 ON T03001.T_NTNLTY_CODE =T02003.T_NTNLTY_CODE LEFT JOIN T12012 ON T03001.T_PAT_NO =T12012.T_PAT_NO  Where T03001.T_PAT_NO ='{patNo}'");
        }

        public DataTable GetDoctor(string lang)
        {
            return Query($"Select T02039.T_DOC_CODE , T_NAME_GIVEN ||' '||T_NAME_FATHER ||''||T_NAME_GFATHER ||' '||T_NAME_FAMILY DOCTOR_NAME_ENG, T_NAME_GIVEN_ARB ||' '||T_NAME_FATHER_ARB  ||' '||T_NAME_GFATHER_ARB||' '||T_NAME_FAMILY_ARB DOCTOR_NAME_ARB from T02039 JOIN T02029 ON T02039.T_DOC_CODE =T02029.T_EMP_NO");
        }

        public DataTable GetABO(string lang)
        {
            return Query($"SELECT T_LANG{lang}_NAME LANG_NAME,T_ABO_CODE FROM T12004");
        }

        public DataTable Getsergeon(string lang)
        {
            return Query($"Select T02039.T_DOC_CODE , T_NAME_GIVEN ||' '||T_NAME_FATHER ||''||T_NAME_GFATHER ||' '||T_NAME_FAMILY DOCTOR_NAME_ENG, T_NAME_GIVEN_ARB ||' '||T_NAME_FATHER_ARB  ||' '||T_NAME_GFATHER_ARB||' '||T_NAME_FAMILY_ARB DOCTOR_NAME_ARB from T02039 JOIN T02029 ON T02039.T_DOC_CODE =T02029.T_EMP_NO");
        }

        public DataTable GetProductData(string lang)
        {
            return Query($"select T_LANG{lang}_NAME T_LANG2_NAME,T_PRODUCT_CODE from t12011 where T_ACTIVE is not null  AND t_frequest is not null order by 1");
        }

        public DataTable GethospitalData(string lang)
        {
           /// return Query($"select T_BANK_CODE T_SITE_CODE,T_LANG{lang}_NAME T_HOSPITAL_NAME from T12337 where T_ZONE_CODE = (select T_ZONE_CODE from T02065 where T_SITE_CODE ='0001' ) AND T_BANK_TYPE = '1'");

             return Query($"select T_LANG{lang}_NAME T_HOSPITAL_NAME,T_HOSP_CODE T_SITE_CODE from T02048");
        }

        public DataTable GetCheckData(string lang)
        {
            return Query($"select T_LANG{lang}_NAME T_CHECK_NAME,T_PRTY_CODE from t12001");
        }

        public DataTable GetWardData(string lang,string siteCode)
        {
            return Query($"SELECT T_LANG{lang}_NAME T_WARD_NAME,T_LOC_CODE FROM T02042 WHERE T_HOSP_CODE='{siteCode}'");
        }

        public DataTable GetNurseData(string lang, string siteCode)
        {
            return Query($"SELECT T_LANG{lang}_NAME_GIVEN||' '||T_LANG{lang}_NAME_FAMILY NAME_NURSE,T_RESOURCE_CODE  FROM t02055 WHERE T_SITE_CODE='{siteCode}' ORDER BY 1");
            // return Query($"SELECT T_LANG2_NAME_GIVEN||' '||T_LANG2_NAME_FAMILY NAME_ENG,T_LANG1_NAME_GIVEN||' '||T_LANG1_NAME_FAMILY NAME_ARB,T_RESOURCE_CODE FROM t02055 WHERE T_SITE_CODE='001' ORDER BY 1");
        }

        public string SaveData(M12300 t12300, string lang, string user, string sitCode)
        {
            string sms = "";
            int count = 0;
            //var accept = Query($"SELECT NVL (T_REQ_STATUS,0)T_REQ_STATUS FROM T12012 WHERE T_REQUEST_NO ='{t12300.T_REQUEST_NO}'").Rows[0]["T_REQ_STATUS"].ToString();
            var accept = Query($"select decode(cnt_req,0,'0',T_REQ_STATUS)T_REQ_STATUS, cnt_req from ( select T_REQ_STATUS,T_REQUEST_NO, decode(T_REQUEST_NO,'{t12300.T_REQUEST_NO}',1,0)cnt_req FROM T12012 WHERE T_REQUEST_NO = '{t12300.T_REQUEST_NO}' or 1=1 order by cnt_req desc) t where rownum=1").Rows[0]["T_REQ_STATUS"].ToString();
            if (accept=="1")
            {
                sms = GetUserMsg("S0715", "LANG" + lang) + "+" + t12300.T_REQUEST_NO; 
            }
            else
            {
           
            int chk = Query($"Select T_REQUEST_NO from T12012 where T_REQUEST_NO ='{t12300.T_REQUEST_NO}'").Rows.Count;
            BeginTransaction();
            if (chk<1)
            {
            string maxRequest = Query("select lpad( nvl(max(NVL(to_number(T_REQUEST_NO),0)),0)+1,8,'0') T_REQUEST_NO from T12012").Rows[0]["T_REQUEST_NO"].ToString();
          
            if (t12300.T_PAT_NO !="")
            {
                Command("INSERT INTO T12012(T_ENTRY_DATE,T_ENTRY_USER, T_REQUEST_NO,T_ABO_CODE, T_ANEMIA_HB," +
                        "T_CHECK_BOX,T_CHECK_BOX_DATE,T_CHECK_BOX_TIME,T_COAGULOPATHY_PT," +
                        "T_CONSULTANT_CODE,T_HOSP_CODE,T_LOCATION_CODE,T_MTHR_BG_CODE,T_NURSE_CODE," +
                        "T_PAT_NO,T_REQUEST_DATE,T_REQUEST_TIME,T_SURGEON_CODE,T_SURGEON_DATE," +
                        "T_SURGEON_TIME,T_THROMBOCYTOPENIA,T_UNITNO,T_VERIFIED_BY,T_VERIFY_DATE,T_VERIFY_TIME," +
                        "T_CLINICAL_DIAGNOSIS,T_SPI_IRRADIATED,T_SPI_LEUKOCYTE,T_SPI_VOL,T_SPI_VOL_ML," +
                        "T_COAGULOPATHY_FIB,T_OTHERS,T_POST_TRANSF_REACTION_YN,T_PREV_PREGNANCIES_YN," +
                        "T_PREV_TRANSFUSION_YN,T_TRANSFUSION_NONE,T_PREV_UN_EXPECTED_ANTIBODY,T_WITHOUT," + "T_BLEEP_NO,T_X_MATCH_WITHOUT_BLOOD,T_X_MATCH_WITH_BLOOD,T_IMMEDIATE_SPIN_X,T_DOC_CODE,T_REQUISITION,T_COAGULOPATHY_APPT,T_SITE_CODE)"
                        + $" VALUES (SYSDATE, '{user}','{maxRequest}', " +
                        $"'{t12300.T_ABO_CODE}','{t12300.T_ANEMIA_HB}','{t12300.T_CHECK_BOX}'," +
                        $"'{t12300.T_CHECK_BOX_DATE}','{t12300.T_CHECK_BOX_TIME}','{t12300.T_COAGULOPATHY_PT}'," +
                        $"'{t12300.T_CONSULTANT_CODE}','{t12300.T_HOSP_CODE}','{t12300.T_LOCATION_CODE}'," +
                        $"'{t12300.T_MTHR_BG_CODE}','{t12300.T_NURSE_CODE}','{t12300.T_PAT_NO}'," +
                        $"'{t12300.T_REQUEST_DATE}','{t12300.T_REQUEST_TIME}'," +
                        $"'{t12300.T_SURGEON_CODE}','{t12300.T_SURGEON_DATE}','{t12300.T_SURGEON_TIME}', " +
                        $"'{t12300.T_THROMBOCYTOPENIA}', '{t12300.T_UNITNO}', '{t12300.T_VERIFIED_BY}', " +
                        $"'{t12300.T_VERIFY_DATE}', '{t12300.T_VERIFY_TIME}','{t12300.T_CLINICAL_DIAGNOSIS}'," +
                        $"'{t12300.T_SPI_IRRADIATED}','{t12300.T_SPI_LEUKOCYTE}','{t12300.T_SPI_VOL}'," +
                        $"'{t12300.T_SPI_VOL_ML}','{t12300.T_COAGULOPATHY_FIB}','{t12300.T_OTHERS}'," +
                        $"'{t12300.T_POST_TRANSF_REACTION_YN}','{t12300.T_PREV_PREGNANCIES_YN}'," +
                        $"'{t12300.T_PREV_TRANSFUSION_YN}','{t12300.T_TRANSFUSION_NONE}'," +
                        $"'{t12300.T_PREV_UN_EXPECTED_ANTIBODY}','{t12300.T_WITHOUT}','{t12300.T_BLEEP_NO}', " +
                        $"'{t12300.T_X_MATCH_WITHOUT_BLOOD}', '{t12300.T_X_MATCH_WITH_BLOOD}', " +$"'{t12300.T_IMMEDIATE_SPIN_X}','{t12300.T_DOC_CODE}','{t12300.T_REQUISITION}','{t12300.T_COAGULOPATHY_APPT}','{sitCode}')");
               
               
                sms = GetUserMsg("N0040", "LANG" + lang) + "+" + maxRequest;
                 count = 1;
            }
          }
            else
            {
                Command($"UPDATE T12012  SET T_UPD_DATE=SYSDATE,T_UPD_USER='{user}',T_ABO_CODE = '{t12300.T_ABO_CODE}',T_ANEMIA_HB='{t12300.T_ANEMIA_HB}',T_CHECK_BOX='{t12300.T_CHECK_BOX}',T_CHECK_BOX_DATE ='{t12300.T_CHECK_BOX_DATE}',T_CHECK_BOX_TIME='{t12300.T_CHECK_BOX_TIME}',              T_COAGULOPATHY_PT='{t12300.T_COAGULOPATHY_PT}',T_CONSULTANT_CODE='{t12300.T_CONSULTANT_CODE}',T_HOSP_CODE='{t12300.T_HOSP_CODE}',T_LOCATION_CODE='{t12300.T_LOCATION_CODE}',T_MTHR_BG_CODE='{t12300.T_MTHR_BG_CODE}',T_NURSE_CODE='{t12300.T_NURSE_CODE}',T_REQUEST_DATE='{t12300.T_REQUEST_DATE}',T_REQUEST_TIME='{t12300.T_REQUEST_TIME}',T_SURGEON_CODE='{t12300.T_SURGEON_CODE}',T_SURGEON_DATE='{t12300.T_SURGEON_DATE}',T_SURGEON_TIME='{t12300.T_SURGEON_TIME}',T_THROMBOCYTOPENIA='{t12300.T_THROMBOCYTOPENIA}',T_UNITNO='{t12300.T_UNITNO}',T_VERIFIED_BY='{t12300.T_VERIFIED_BY}',T_VERIFY_DATE='{t12300.T_VERIFY_DATE}',T_VERIFY_TIME='{t12300.T_VERIFY_TIME}',T_CLINICAL_DIAGNOSIS='{t12300.T_CLINICAL_DIAGNOSIS}',T_SPI_IRRADIATED='{t12300.T_SPI_IRRADIATED}',T_SPI_LEUKOCYTE='{t12300.T_SPI_LEUKOCYTE}',T_SPI_VOL='{t12300.T_SPI_VOL}',T_SPI_VOL_ML='{t12300.T_SPI_VOL_ML}',T_COAGULOPATHY_FIB='{t12300.T_COAGULOPATHY_FIB}',T_OTHERS='{t12300.T_OTHERS}',T_POST_TRANSF_REACTION_YN='{t12300.T_POST_TRANSF_REACTION_YN}',T_PREV_PREGNANCIES_YN='{t12300.T_PREV_PREGNANCIES_YN}',T_PREV_TRANSFUSION_YN='{t12300.T_PREV_TRANSFUSION_YN}',T_TRANSFUSION_NONE='{t12300.T_TRANSFUSION_NONE}',T_PREV_UN_EXPECTED_ANTIBODY='{t12300.T_PREV_UN_EXPECTED_ANTIBODY}',T_WITHOUT='{t12300.T_WITHOUT}',T_BLEEP_NO='{t12300.T_BLEEP_NO}',T_X_MATCH_WITHOUT_BLOOD='{t12300.T_X_MATCH_WITHOUT_BLOOD}',T_X_MATCH_WITH_BLOOD='{t12300.T_X_MATCH_WITH_BLOOD}',T_IMMEDIATE_SPIN_X='{t12300.T_IMMEDIATE_SPIN_X}',T_DOC_CODE='{t12300.T_DOC_CODE}',T_REQUISITION='{t12300.T_REQUISITION}',T_COAGULOPATHY_APPT='{t12300.T_COAGULOPATHY_APPT}',T_SITE_CODE='{sitCode}' WHERE T_REQUEST_NO='{t12300.T_REQUEST_NO}' AND T_PAT_NO = '{t12300.T_PAT_NO}'");

                sms = GetUserMsg("N0041", "LANG" + lang) + "+" + t12300.T_REQUEST_NO;
                count = 1;
            }
                if (count == 1)
                {
                    CommitTransaction();
                }
                else
                {
                    RollbackTransaction();
                }
            }
            return sms;
        }

        public DataTable GeAllData(string patNo, string lang)
        {
            return Query($"SELECT T_ABO_CODE,T_ANEMIA_HB,T_CHECK_BOX,T_REQUISITION,T_CHECK_BOX_DATE  ,T_CHECK_BOX_TIME,T_COAGULOPATHY_PT,T_CONSULTANT_CODE,t12.T_HOSP_CODE,T_LOCATION_CODE  ,T_MTHR_BG_CODE ,T_NURSE_CODE ,T_PAT_NO,T_REQUEST_DATE  ,T_REQUEST_NO ,T_REQUEST_TIME ,T_SURGEON_CODE ,T_SURGEON_DATE  ,T_SURGEON_TIME   ,T_THROMBOCYTOPENIA,T_UNITNO,T_VERIFIED_BY  ,T_VERIFY_DATE   ,T_VERIFY_TIME,T_CLINICAL_DIAGNOSIS,T_SPI_IRRADIATED,T_SPI_LEUKOCYTE,T_SPI_VOL,T_SPI_VOL_ML,T_COAGULOPATHY_FIB,T_OTHERS,T_POST_TRANSF_REACTION_YN,T_PREV_PREGNANCIES_YN,T_PREV_TRANSFUSION_YN,T_TRANSFUSION_NONE,T_PREV_UN_EXPECTED_ANTIBODY,T_WITHOUT,T_BLEEP_NO,T_X_MATCH_WITHOUT_BLOOD,T_X_MATCH_WITH_BLOOD,T_IMMEDIATE_SPIN_X, T_DOC_CODE,T_COAGULOPATHY_APPT,(Select  T_NAME_GIVEN ||' '||T_NAME_FATHER ||''||T_NAME_GFATHER ||' '||T_NAME_FAMILY DOCTOR_NAME_ENG from T12012 JOIN T02029 ON T12012.T_DOC_CODE =T02029.T_EMP_NO where T_PAT_NO = '{patNo}') DOCTOR_NAME_ENG,(Select T_NAME_GIVEN_ARB ||' '||T_NAME_FATHER_ARB  ||' '||T_NAME_GFATHER_ARB||' '||T_NAME_FAMILY_ARB DOCTOR_NAME_ARB from T12012 JOIN T02029 ON T12012.T_DOC_CODE =T02029.T_EMP_NO where T_PAT_NO = '{patNo}')DOCTOR_NAME_ARB,(Select  T_NAME_GIVEN ||' '||T_NAME_FATHER ||''||T_NAME_GFATHER ||' '||T_NAME_FAMILY DOCTOR_NAME_ENG from T12012 JOIN T02029 ON T12012.T_CONSULTANT_CODE =T02029.T_EMP_NO where T_PAT_NO = '{patNo}') CONSULTANT_NAME_ENG,(Select T_NAME_GIVEN_ARB ||' '||T_NAME_FATHER_ARB  ||' '||T_NAME_GFATHER_ARB||' '||T_NAME_FAMILY_ARB DOCTOR_NAME_ARB from T12012 JOIN T02029 ON T12012.T_CONSULTANT_CODE =T02029.T_EMP_NO where T_PAT_NO = '{patNo}')CONSULTANT_NAME_ARB,(Select  T_NAME_GIVEN ||' '||T_NAME_FATHER ||''||T_NAME_GFATHER ||' '||T_NAME_FAMILY DOCTOR_NAME_ENG from T12012 JOIN T02029 ON T12012.T_SURGEON_CODE =T02029.T_EMP_NO where T_PAT_NO = '{patNo}') T_SURGEON_NAME_ENG,(Select  T_NAME_GIVEN ||' '||T_NAME_FATHER ||''||T_NAME_GFATHER ||' '||T_NAME_FAMILY DOCTOR_NAME_ENG from T12012 JOIN T02029 ON T12012.T_SURGEON_CODE =T02029.T_EMP_NO where T_PAT_NO = '{patNo}') T_SURGEON_NAME_ARB,(SELECT T_LANG{lang}_NAME LANG_NAME FROM T12012 JOIN T12004 ON T12012.T_ABO_CODE =T12004.T_ABO_CODE where T_PAT_NO = '{patNo}')T_ABO_NAME,(SELECT T_LANG{lang}_NAME LANG_NAME FROM T12012 JOIN T12004 ON T12012.T_ABO_CODE =T12004.T_ABO_CODE where T_PAT_NO = '{patNo}')T_MTR_BG,(SELECT T_LANG{lang}_NAME_GIVEN||' '||T_LANG{lang}_NAME_FAMILY NAME_NURSE FROM T12012 JOIN t02055 ON T12012.T_NURSE_CODE =t02055.T_RESOURCE_CODE WHERE T_PAT_NO = '{patNo}')T_NURSE_NAME,(SELECT T_LANG{lang}_NAME_GIVEN||' '||T_LANG{lang}_NAME_FAMILY NAME_NURSE FROM T12012 JOIN t02055 ON T12012.T_VERIFIED_BY =t02055.T_RESOURCE_CODE WHERE T_PAT_NO = '{patNo}')T_VERIFIED_NAME,t42.T_LANG{lang}_NAME T_LOCATION_NAME,t48.T_LANG{lang}_NAME T_HOSPITAL_NAME ,t01.T_LANG{lang}_NAME T_CHECK_NAME,t11.T_LANG{lang}_NAME T_PRODUCT_NAME ,t33.T_LANG{lang}_NAME T_VIRUS_NAME FROM T12012 t12  LEFT JOIN T02042 t42 ON t12.T_LOCATION_CODE = t42.T_LOC_CODE  LEFT JOIN T02048 t48 ON t12.T_HOSP_CODE = t48.T_HOSP_CODE  LEFT JOIN t12001 t01 ON t12.T_CHECK_BOX = t01.T_PRTY_CODE  LEFT JOIN t12011 t11 ON t12.T_REQUISITION = t11.T_PRODUCT_CODE LEFT JOIN t12033 t33 ON t12.T_WITHOUT = t33.T_VIRUS_CODE where T_PAT_NO = '{patNo}'");

            // return Query($"SELECT T_ABO_CODE,  T_ANEMIA_HB,  T_CHECK_BOX,  T_REQUISITION,  T_CHECK_BOX_DATE ,  T_CHECK_BOX_TIME,  T_COAGULOPATHY_PT,  T_CONSULTANT_CODE,  t12.T_HOSP_CODE,  T_LOCATION_CODE ,  T_MTHR_BG_CODE ,  T_NURSE_CODE ,  T_PAT_NO,  T_REQUEST_DATE ,  T_REQUEST_NO ,  T_REQUEST_TIME ,  T_SURGEON_CODE ,  T_SURGEON_DATE ,  T_SURGEON_TIME ,  T_THROMBOCYTOPENIA,  T_UNITNO,  T_VERIFIED_BY ,  T_VERIFY_DATE ,  T_VERIFY_TIME,  T_CLINICAL_DIAGNOSIS,  T_SPI_IRRADIATED,  T_SPI_LEUKOCYTE,  T_SPI_VOL,  T_SPI_VOL_ML,  T_COAGULOPATHY_FIB,  T_OTHERS,  T_POST_TRANSF_REACTION_YN,  T_PREV_PREGNANCIES_YN,  T_PREV_TRANSFUSION_YN,  T_TRANSFUSION_NONE,  T_PREV_UN_EXPECTED_ANTIBODY,  T_WITHOUT,  T_BLEEP_NO,  T_X_MATCH_WITHOUT_BLOOD,  T_X_MATCH_WITH_BLOOD,  T_IMMEDIATE_SPIN_X,  T_DOC_CODE,  T_COAGULOPATHY_APPT,  (SELECT T_NAME_GIVEN    ||' '    ||T_NAME_FATHER    ||''    ||T_NAME_GFATHER    ||' '    ||T_NAME_FAMILY DOCTOR_NAME_ENG  FROM T12012  JOIN T02029  ON T12012.T_DOC_CODE =T02029.T_EMP_NO  WHERE T_PAT_NO       = '00000002' and   T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  ) DOCTOR_NAME_ENG,  (SELECT T_NAME_GIVEN_ARB    ||' '    ||T_NAME_FATHER_ARB    ||' '    ||T_NAME_GFATHER_ARB    ||' '    ||T_NAME_FAMILY_ARB DOCTOR_NAME_ARB  FROM T12012  JOIN T02029  ON T12012.T_DOC_CODE =T02029.T_EMP_NO  WHERE T_PAT_NO       = '00000002'   and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  )DOCTOR_NAME_ARB,  (SELECT T_NAME_GIVEN    ||' '    ||T_NAME_FATHER    ||''    ||T_NAME_GFATHER    ||' '    ||T_NAME_FAMILY DOCTOR_NAME_ENG  FROM T12012  JOIN T02029  ON T12012.T_CONSULTANT_CODE =T02029.T_EMP_NO  WHERE T_PAT_NO              = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  ) CONSULTANT_NAME_ENG,  (SELECT T_NAME_GIVEN_ARB    ||' '    ||T_NAME_FATHER_ARB    ||' '    ||T_NAME_GFATHER_ARB    ||' '    ||T_NAME_FAMILY_ARB DOCTOR_NAME_ARB  FROM T12012  JOIN T02029  ON T12012.T_CONSULTANT_CODE =T02029.T_EMP_NO  WHERE T_PAT_NO              = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  )CONSULTANT_NAME_ARB,  (SELECT T_NAME_GIVEN    ||' '    ||T_NAME_FATHER    ||''    ||T_NAME_GFATHER    ||' '    ||T_NAME_FAMILY DOCTOR_NAME_ENG  FROM T12012  JOIN T02029  ON T12012.T_SURGEON_CODE =T02029.T_EMP_NO  WHERE T_PAT_NO           = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  ) T_SURGEON_NAME_ENG,  (SELECT T_NAME_GIVEN    ||' '    ||T_NAME_FATHER    ||''    ||T_NAME_GFATHER    ||' '    ||T_NAME_FAMILY DOCTOR_NAME_ENG  FROM T12012  JOIN T02029  ON T12012.T_SURGEON_CODE =T02029.T_EMP_NO  WHERE T_PAT_NO           = '00000002'   and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  ) T_SURGEON_NAME_ARB,  (SELECT T_LANG2_NAME LANG_NAME  FROM T12012  JOIN T12004  ON T12012.T_ABO_CODE =T12004.T_ABO_CODE  WHERE T_PAT_NO       = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  )T_ABO_NAME,  (SELECT T_LANG2_NAME LANG_NAME  FROM T12012  JOIN T12004  ON T12012.T_ABO_CODE =T12004.T_ABO_CODE  WHERE T_PAT_NO       = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  )T_MTR_BG,  (SELECT T_LANG2_NAME_GIVEN    ||' '    ||T_LANG2_NAME_FAMILY NAME_NURSE  FROM T12012  JOIN t02055  ON T12012.T_NURSE_CODE =t02055.T_RESOURCE_CODE  WHERE T_PAT_NO         = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  )T_NURSE_NAME,  (SELECT T_LANG2_NAME_GIVEN    ||' '    ||T_LANG2_NAME_FAMILY NAME_NURSE  FROM T12012  JOIN t02055  ON T12012.T_VERIFIED_BY =t02055.T_RESOURCE_CODE  WHERE T_PAT_NO = '00000002'  and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')  )T_VERIFIED_NAME,  t42.T_LANG2_NAME T_LOCATION_NAME,  t48.T_LANG2_NAME T_HOSPITAL_NAME ,  t01.T_LANG2_NAME T_CHECK_NAME,  t11.T_LANG2_NAME T_PRODUCT_NAME ,  t33.T_LANG2_NAME T_VIRUS_NAME FROM T12012 t12 LEFT JOIN T02042 t42 ON t12.T_LOCATION_CODE = t42.T_LOC_CODE LEFT JOIN T02048 t48 ON t12.T_HOSP_CODE = t48.T_HOSP_CODE LEFT JOIN t12001 t01 ON t12.T_CHECK_BOX = t01.T_PRTY_CODE LEFT JOIN t12011 t11 ON t12.T_REQUISITION = t11.T_PRODUCT_CODE LEFT JOIN t12033 t33 ON t12.T_WITHOUT = t33.T_VIRUS_CODE WHERE T_PAT_NO   = '00000002' and T_REQUEST_NO =(select MAX(T_REQUEST_NO)from T12012 where T_PAT_NO= '00000002')");
        }


        public DataTable GetVirusData(string lang)
        {
            return Query($"Select T_LANG{lang}_NAME T_VIRUS_NAME,T_VIRUS_CODE from T12033");
        }
    }
}