using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace BloodBankDAL.Repository.Query.Report
{
    public class R12260:CommonDAL
    {
        public DataTable GetInforData(string site, string lang)
        {
          return  Query($"select T_SITE_CODE , T_COUNTRY_LANG1_NAME , T_COUNTRY_LANG2_NAME , T_MIN_LANG1_NAME , T_MIN_LANG2_NAME , T_SITE_LANG1_NAME , T_SITE_LANG2_NAME , T_LOGO_ID , T_LOGO_NAME , T_LOGO , t_lcence_no from t01028 where t_site_code='{site}'");
        }

        public DataTable GetDetails(string site, string fromDate, string toDate)
        {
            return Query($"SELECT T12022.T_UNIT_NO||' '||T12022.T_DONATION_TIME donation_time,T12022.T_PIN, T12022.t_donation_date||' '||TO_CHAR(T12022.T_DONATION_DATE,'DAY')T_DATE_DAY,TRUNC(TO_DATE(T12022.T_DONATION_DATE,'DD-MON-YY'))T_DONATION_DATE, (SELECT T_USER_NAME FROM T01009 WHERE T_PIN='2222' AND ROWNUM=1)T_USER_NAME FROM T12022 JOIN T12017 ON T12017.T_REQUEST_ID = T12022.T_REQUEST_ID WHERE TO_DATE(T12022.T_DONATION_DATE,'DD/MM/YYYY') between TO_DATE('{fromDate}','DD/MM/YYYY') and TO_DATE('{toDate}','DD/MM/YYYY') and t_unit_no is not null and t_pin is not null and t_pin='2222' AND T12017.T_SITE_CODE ='{site}' order by TO_DATE(T12022.t_donation_date,'DD/MM/RRRR'),DONATION_TIME");
            // return Query($"SELECT T12022.T_UNIT_NO||' '||T12022.T_DONATION_TIME donation_time,T12022.T_PIN, T12022.t_donation_date||' '||TO_CHAR(T12022.T_DONATION_DATE,'DAY')T_DATE_DAY,TRUNC(TO_DATE(T12022.T_DONATION_DATE,'DD-MON-YY'))T_DONATION_DATE, (SELECT T_USER_NAME FROM T01009 WHERE T_PIN='2222' AND ROWNUM=1)T_USER_NAME FROM T12022 JOIN T12017 ON T12017.T_REQUEST_ID = T12022.T_REQUEST_ID WHERE TO_DATE(T12022.T_DONATION_DATE,'DD/MM/YYYY') between TO_DATE('1/06/18','DD/MM/YYYY') and TO_DATE('17/06/19','DD/MM/YYYY') and t_unit_no is not null and t_pin is not null and t_pin='2222' AND T12017.T_SITE_CODE ='{site}' order by TO_DATE(T12022.t_donation_date,'DD/MM/RRRR'),DONATION_TIME");
        }

        public DataTable getDate(string site, string f, string t)
        {
            return Query($"SELECT TO_CHAR( T12022.T_DONATION_DATE,'DD/MM/YY') T_DATE, T12022.t_donation_date ||' ' ||TO_CHAR(T12022.T_DONATION_DATE,'DAY')T_DATE_DAY, COUNT(*)T_COUNT FROM T12022 JOIN T12017 ON T12017.T_REQUEST_ID = T12022.T_REQUEST_ID WHERE TO_DATE(T12022.T_DONATION_DATE,'DD/MM/YYYY') BETWEEN TO_DATE('{f}','DD/MM/YYYY') AND TO_DATE('{t}','DD/MM/YYYY') AND t_unit_no IS NOT NULL AND t_pin IS NOT NULL AND t_pin ='2222' AND T12017.T_SITE_CODE ='0001' GROUP BY TO_CHAR( T12022.T_DONATION_DATE,'DD/MM/YY'), T12022.t_donation_date ||' ' ||TO_CHAR(T12022.T_DONATION_DATE,'DAY')");

            // return Query($"SELECT DISTINCT TO_CHAR( T12022.T_DONATION_DATE,'DD/MM/YY') T_DATE, T12022.t_donation_date   ||' '   ||TO_CHAR(T12022.T_DONATION_DATE,'DAY')T_DATE_DAY  FROM T12022 JOIN T12017 ON T12017.T_REQUEST_ID = T12022.T_REQUEST_ID WHERE TO_DATE(T12022.T_DONATION_DATE,'DD/MM/YYYY') BETWEEN TO_DATE('{f}','DD/MM/YYYY') AND TO_DATE('{t}','DD/MM/YYYY') AND t_unit_no IS NOT NULL AND t_pin IS NOT NULL AND t_pin ='2222' AND T12017.T_SITE_CODE ='{site}' GROUP BY T12022.T_DONATION_DATE,'DD/MM/YYYY'");
        }

        public DataTable showReport(string site, string f, string t)
        {
            return Query($"SELECT T12022.T_UNIT_NO ||' ' ||T12022.T_DONATION_TIME donation_time, T12022.T_PIN, T12022.t_donation_date ||' ' ||TO_CHAR(T12022.T_DONATION_DATE,'DAY')T_DATE_DAY, TRUNC(TO_DATE(T12022.T_DONATION_DATE,'DD-MON-YY'))T_DONATION_DATE,TO_CHAR( T12022.T_DONATION_DATE,'DD/MM/YY') T_DATE, (SELECT T_USER_NAME FROM T01009 WHERE T_PIN='2222' AND ROWNUM=1 )T_USER_NAME FROM T12022 JOIN T12017 ON T12017.T_REQUEST_ID = T12022.T_REQUEST_ID WHERE TO_DATE(T12022.T_DONATION_DATE,'DD/MM/YYYY') BETWEEN TO_DATE('{f}','DD/MM/YYYY') AND TO_DATE('{t}','DD/MM/YYYY') AND t_unit_no IS NOT NULL AND t_pin IS NOT NULL AND t_pin ='2222' AND T12017.T_SITE_CODE ='{site}' ORDER BY TO_DATE(T12022.t_donation_date,'DD/MM/RRRR'), DONATION_TIME");
        }

        public DataTable getTimeData(string site, object f, object t)
        {
            return Query($"Select Table1.T_DATE, COUNT(*)T_COUNT_TIME from( SELECT TO_CHAR( T12022.T_DONATION_DATE,'DD/MM/YY') T_DATE, SUBSTR(T12022.T_DONATION_TIME,1,2) T_DONATION_TIME, COUNT(*)T_COUNT_1 FROM T12022 JOIN T12017 ON T12017.T_REQUEST_ID = T12022.T_REQUEST_ID WHERE TO_DATE(T12022.T_DONATION_DATE,'DD/MM/YYYY') BETWEEN TO_DATE('{f}','DD/MM/YYYY') AND TO_DATE('{t}','DD/MM/YYYY') AND t_unit_no IS NOT NULL AND t_pin IS NOT NULL AND t_pin ='2222' AND T12017.T_SITE_CODE ='0001' GROUP BY TO_CHAR( T12022.T_DONATION_DATE,'DD/MM/YY'), SUBSTR(T12022.T_DONATION_TIME,1,2) )Table1 GROUP BY Table1.T_DATE");
        }
    }
}