using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace BloodBankDAL.Repository.Query.Query
{
    public class Q12017:CommonDAL
    {
        public DataTable GetAllData(string REQUEST_NO, string lang)
        {
            return Query($"SELECT T12.T_REQUEST_NO ,T12.T_REQUEST_DATE ,T12.T_REQUEST_TIME ,T12.T_ABO_CODE ,T04.T_LANG{lang}_NAME ABO_DESC,T12.T_LOCATION_CODE ,T12.T_REQ_STATUS,T06.T_LANG{lang}_NAME REQ_STATUS_DESC,T12.T_PAT_NO,T42.T_LANG{lang}_NAME LOC_DESC,T12.T_UNITNO REQ_UNIT,NVL(V24.COUNT_UNIT,0) XMATCHE_UNIT,NVL(V25.COUNT_UNIT,0) UNIT_RELEASE FROM T12012 T12 LEFT JOIN T12004 T04 ON T12.T_ABO_CODE=T04.T_ABO_CODE LEFT JOIN T12106 T06 ON T12.T_REQ_STATUS=T06.T_STATUS_ID AND T_STATUS_TYPE=2 LEFT JOIN T02042 T42 ON T12.T_LOCATION_CODE=T42.T_LOC_CODE LEFT JOIN V12024 V24 ON V24.REQUEST_NO=T12.T_REQUEST_NO LEFT JOIN V12025 V25 ON V25.REQUEST_NO=T12.T_REQUEST_NO WHERE T12.T_REQUEST_DATE >= TRUNC(SYSDATE) -700 AND T12.T_REQUEST_NO ='{REQUEST_NO}'  ORDER BY T12.T_REQUEST_NO DESC");
        }
    }
}