using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace BloodBankDAL.Repository.Query.Query
{
    public class Q12263 : CommonDAL
    {
        internal DataTable GetGridData(string siteCode, string referCode)
        {
            return Query($"SELECT T_REQ_ID, T12337.T_LANG2_NAME T_HOSPITAL, T12337.T_BANK_CODE, T01009.T_USER_NAME T_DELIVERY_MAN, T12091.T_EMP_CODE, T_BLOOD_REQ_NO, T12091.T_ENTRY_DATE, T12091.T_ENTRY_TIME, ( CASE WHEN T_BLOOD_DROP_FLG ='1' THEN 'Droped' WHEN T_BLOOD_RCVD_FLG ='1' THEN 'Received' WHEN T_REQ_CANCEL_FLG='1' THEN 'Cancel' WHEN T_REQ_ACCEPT_FLG = '1' THEN 'Accept' WHEN TO_CHAR(T12091.T_ENTRY_DATE )IS NOT NULL THEN 'Requested' ELSE ' ' END ) T_ACPT_CAN, T_REQ_ACCEPT_FLG, ( CASE WHEN TO_CHAR(T_REQ_ACCEPT_DATE) IS NOT NULL THEN TO_CHAR(T_REQ_ACCEPT_DATE) WHEN TO_CHAR(T_REQ_CANCEL_DATE) IS NOT NULL THEN TO_CHAR(T_REQ_CANCEL_DATE) ELSE ' ' END ) T_ACPT_CAN_DATE, ( CASE WHEN T_REQ_ACCEPT_TIME IS NOT NULL THEN T_REQ_ACCEPT_TIME WHEN T_REQ_CANCEL_TIME IS NOT NULL THEN T_REQ_CANCEL_TIME ELSE ' ' END ) T_ACPT_CAN_TIME, T_BLOOD_RCVD_DATE, T_BLOOD_RCVD_TIME, T_REQ_CANCEL_FLG, T_REQ_CANCEL_REASON, T_BLOOD_DROP_DATE, T_BLOOD_DROP_TIME, T_BLOOD_REQ_STATUS, T_ESTIMATED_DELIVERY_TIME, T_BLOOD_RCVD_BY, T_ESTIMATED_DELIVERY_DIST, T_REQ_COM_FLG FROM T12091 JOIN T12337 ON T12091.T_SITE_CODE = T12337.T_BANK_CODE JOIN T01009 ON T12091.T_EMP_CODE = T01009.T_EMP_CODE ORDER BY T_BLOOD_REQ_NO DESC");
        }
    }
}