using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BloodBankDAL.Model
{
    public class T03001
    {
        public DateTime T_UPD_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public DateTime T_ENTRY_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public string T_BIRTH_DATE { get; set; }
        public string T_BIRTH_PLACE { get; set; }
        public DateTime T_ID_ISSUE_DATE { get; set; }
        public string T_ID_ISSUE_PLACE { get; set; }
        public string T_MRTL_STATUS { get; set; }
        public string T_MTHR_PATNO { get; set; }
        public string T_FAMILY_LANG1_NAME { get; set; }
        public string T_FAMILY_LANG2_NAME { get; set; }
        public string T_FATHER_LANG1_NAME { get; set; }
        public string T_FATHER_LANG2_NAME { get; set; }
        public string T_GFATHER_LANG1_NAME { get; set; }
        public string T_GFATHER_LANG2_NAME { get; set; }
        public string T_FIRST_LANG1_NAME { get; set; }
        public string T_FIRST_LANG2_NAME { get; set; }
        public string T_MOTHER_LANG1_NAME { get; set; }
        public string T_MOTHER_LANG2_NAME { get; set; }
        public string T_NTNLTY_CODE { get; set; }
        public string T_NTNLTY_ID { get; set; }
        public DateTime T_PASSPORT_IS_DATE { get; set; }
        public string T_PASSPORT_IS_PLACE { get; set; }
        public string T_PASSPORT_NO { get; set; }
        public string T_PAT_NO { get; set; }
        public string T_PHONE_HOME { get; set; }
        public string T_PHONE_WORK { get; set; }
        public string T_MOBILE_NO { get; set; }
        public string T_POSTAL_CODE { get; set; }
        public string T_ADDRESS1 { get; set; }
        public string T_ADDRESS2 { get; set; }
        public string T_RLGN_CODE { get; set; }
        public string T_RLTN_CODE { get; set; }
        public string T_GENDER { get; set; }
        public string T_CHART_NO { get; set; }
        public string T_COMPANY_CODE { get; set; }
        public string T_PAT_DEATH { get; set; }
        public string T_BLD_GRP { get; set; }
        public string T_X_APPRV_BY { get; set; }
        public string T_X_HOSP1_PAT_NO { get; set; }
        public string T_X_HOSP2_PAT_NO { get; set; }
        public string T_X_HOSP3_PAT_NO { get; set; }
        public string T_X_HOSP4_PAT_NO { get; set; }
        public string T_X_HOSP5_PAT_NO { get; set; }
        public string T_X_HOSP6_PAT_NO { get; set; }
        public string T_X_HOSP7_PAT_NO { get; set; }
        public int T_IP_EPISODES { get; set; }
        public string T_JOB_CODE { get; set; }
        public int T_OP_EPISODES { get; set; }
        public string T_SPONSR_CODE { get; set; }
        public string T_PAYOR_Y { get; set; }
        public int T_BALANCE_AMOUNT { get; set; }
        public string T_X_FOREIGN_MR { get; set; }
        public string T_X_ADM_LOC { get; set; }
        public string T_X_HOSP_NO { get; set; }
        public string T_X_RMC_CHRTNO { get; set; }
        public string T_X_AIDS_PATNO { get; set; }
        public string T_X_AIDS_PATNAME { get; set; }
        public string T_X_DISASTER_ID_NO { get; set; }
        public string T_X_DISASTER_SITE { get; set; }
        public string T_X_PAT_GROUP_CODE { get; set; }
        public string T_X_CNCL_PATNO { get; set; }
        public string T_X_CNCL_USER { get; set; }
        public DateTime T_X_CNCL_DATE { get; set; }
        public string T_X_CNCL_RSN { get; set; }
        public string T_TMP_PAT_NO { get; set; }
        public string T_X_SPONSOR_CODE { get; set; }
        public string T_REF_NO { get; set; }
        public string T_DISP_FILE_NO { get; set; }
        public string T_X_SNDX_FAMILY { get; set; }
        public string T_X_SNDX_FATHER { get; set; }
        public string T_X_SNDX_GFATHER { get; set; }
        public string T_X_SNDX_GIVEN { get; set; }
        public string T_X_SNDX_MOTHER { get; set; }
        public string T_X_DM_PAT_NO { get; set; }
        public string T_X_PCC_CODE { get; set; }
        public string T_X_NEW_PATNO { get; set; }
        public string T_X_PAT_TYPE { get; set; }
        public string T_X_FORM_NAME { get; set; }
        public string T_SMOKER_FLAG { get; set; }
        public string T_CNFDNTL_FLAG { get; set; }
        public string T_X_CNCL_HOSP2_NO { get; set; }
        public string T_X_CNCL_HOSP3_NO { get; set; }
        public string T_X_CNCL_HOSP4_NO { get; set; }
        public string T_X_CNCL_HOSP5_NO { get; set; }
        public string T_X_CNCL_HOSP6_NO { get; set; }
        public string T_X_CNCL_HOSP7_NO { get; set; }
        public string T_X_CNCL_HOSPNO_USER { get; set; }
        public DateTime T_X_CNCL_HOSPNO_DATE { get; set; }
        public string T_X_HOSP8_PAT_NO { get; set; }
        public string T_X_MSG_FLAG { get; set; }
        public string T_CNCL_NTNLTY_ID { get; set; }
        public string T_POBOX_NO { get; set; }
        public string T_EMAIL_ID { get; set; }
        public string T_FAMHD_PAT_NO { get; set; }
        public string T_FAMHD_ID { get; set; }
        public string T_FAMHD_RLTN_CODE { get; set; }
        public string T_FAMHD_NAME { get; set; }
        public string T_ER_CONT_NAME { get; set; }
        public string T_ER_RLTN_CODE { get; set; }
        public string T_ER_MOBILE { get; set; }
        public string T_TRANS_FLAG { get; set; }
        public int T_ENTRY_TIME { get; set; }
        public int T_UPDATE_TIME { get; set; }
        public DateTime T_TRANS_DATE { get; set; }
        public int T_TRANS_TIME { get; set; }
        public string T_TRANS_USER { get; set; }
        public string T_PAT_LANG { get; set; }
        public string T_PAT_TITLE { get; set; }
        public string T_INACTIVE_FLAG { get; set; }
        public string T_REF_LETTER { get; set; }
        public string T_SKIN_COLOR { get; set; }
        public string T_DISTINCTION { get; set; }
        public string T_RELEASE { get; set; }
        public string T_ACCEPTED { get; set; }
        public string T_UNKOWN_NO { get; set; }
        public string T_FILE_INACTIVE { get; set; }
        public DateTime T_INACTIVE_DATE { get; set; }
    }
}